// --- DATABASE (V4 - COMPREHENSIVE EXPANSION) ---
const exerciseDB = {
    'Chest': [
        // Barbell
        { name: 'Barbell Bench Press', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['barbell'] },
        { name: 'Incline Barbell Press', type: 'compound', muscles: ['Upper Pecs', 'Delts'], equipment: ['barbell'] },
        { name: 'Decline Barbell Press', type: 'compound', muscles: ['Lower Pecs', 'Triceps'], equipment: ['barbell'] },
        { name: 'Close Grip Bench Press', type: 'compound', muscles: ['Triceps', 'Pecs'], equipment: ['barbell'] },
        { name: 'Floor Press', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['barbell', 'dumbbells'] },
        // Dumbbell
        { name: 'Dumbbell Bench Press', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['dumbbells'] },
        { name: 'Incline Dumbbell Press', type: 'compound', muscles: ['Upper Pecs', 'Delts'], equipment: ['dumbbells'] },
        { name: 'Decline Dumbbell Press', type: 'compound', muscles: ['Lower Pecs', 'Triceps'], equipment: ['dumbbells'] },
        { name: 'Dumbbell Flyes', type: 'isolation', muscles: ['Pecs'], equipment: ['dumbbells'] },
        { name: 'Incline Dumbbell Flyes', type: 'isolation', muscles: ['Upper Pecs'], equipment: ['dumbbells'] },
        { name: 'Dumbbell Pullover', type: 'compound', muscles: ['Pecs', 'Lats'], equipment: ['dumbbells'] },
        { name: 'Svend Press', type: 'isolation', muscles: ['Pecs'], equipment: ['dumbbells'] },
        { name: 'Dumbbell Squeeze Press', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['dumbbells'] },
        // Machine & Cable
        { name: 'Smith Machine Bench Press', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['machines'] },
        { name: 'Smith Machine Incline Press', type: 'compound', muscles: ['Upper Pecs', 'Triceps'], equipment: ['machines'] },
        { name: 'Machine Chest Press', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['machines'] },
        { name: 'Machine Incline Press', type: 'compound', muscles: ['Upper Pecs', 'Triceps'], equipment: ['machines'] },
        { name: 'Pec Deck Machine', type: 'isolation', muscles: ['Pecs'], equipment: ['machines'] },
        { name: 'Machine Fly', type: 'isolation', muscles: ['Pecs'], equipment: ['machines'] },
        { name: 'Cable Crossover (High to Low)', type: 'isolation', muscles: ['Lower Pecs'], equipment: ['cable'] },
        { name: 'Cable Crossover (Low to High)', type: 'isolation', muscles: ['Upper Pecs'], equipment: ['cable'] },
        { name: 'Cable Fly', type: 'isolation', muscles: ['Pecs'], equipment: ['cable'] },
        // Bodyweight & Calisthenics
        { name: 'Push-ups', type: 'compound', muscles: ['Pecs', 'Triceps', 'Core'], equipment: ['bodyweight'] },
        { name: 'Incline Push-ups', type: 'compound', muscles: ['Lower Pecs', 'Triceps'], equipment: ['bodyweight'] },
        { name: 'Decline Push-ups', type: 'compound', muscles: ['Upper Pecs', 'Triceps'], equipment: ['bodyweight'] },
        { name: 'Dips (Chest Focused)', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['bodyweight'] },
        { name: 'Wide Grip Push-ups', type: 'compound', muscles: ['Pecs'], equipment: ['bodyweight'] },
        { name: 'Diamond Push-ups', type: 'compound', muscles: ['Triceps', 'Pecs'], equipment: ['bodyweight'] },
        { name: 'Pseudo Planche Push-ups', type: 'compound', muscles: ['Pecs', 'Delts', 'Triceps'], equipment: ['bodyweight'], details: 'Advanced: lean forward.' },
        { name: 'Archer Push-ups', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['bodyweight'], details: 'Unilateral focus.' },
        { name: 'Explosive Push-ups', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['bodyweight'], details: 'Plyometric.' },
    ],
    'Back': [
        // Deadlifts (often considered back or full body)
        { name: 'Conventional Deadlift', type: 'compound', muscles: ['Full Body', 'Lower Back', 'Glutes', 'Hamstrings'], equipment: ['barbell'] },
        { name: 'Sumo Deadlift', type: 'compound', muscles: ['Glutes', 'Hamstrings', 'Adductors', 'Lower Back'], equipment: ['barbell'] },
        { name: 'Rack Pull', type: 'compound', muscles: ['Upper Back', 'Traps', 'Lower Back'], equipment: ['barbell'] },
        // Barbell & Dumbbell Rows
        { name: 'Barbell Bent Over Row', type: 'compound', muscles: ['Lats', 'Rhomboids', 'Biceps'], equipment: ['barbell'] },
        { name: 'Pendlay Row', type: 'compound', muscles: ['Lats', 'Upper Back'], equipment: ['barbell'] },
        { name: 'T-Bar Row', type: 'compound', muscles: ['Lats', 'Mid-Back'], equipment: ['barbell', 'machines'] },
        { name: 'Dumbbell Row', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['dumbbells'] },
        { name: 'Chest Supported Dumbbell Row', type: 'compound', muscles: ['Upper Back', 'Lats'], equipment: ['dumbbells'] },
        { name: 'Renegade Row', type: 'compound', muscles: ['Back', 'Core', 'Biceps'], equipment: ['dumbbells', 'kettlebell'] },
        // Pull-ups & Pulldowns
        { name: 'Pull-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'] },
        { name: 'Chin-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'] },
        { name: 'Neutral Grip Pull-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'] },
        { name: 'Wide Grip Pull-ups', type: 'compound', muscles: ['Lats'], equipment: ['bodyweight'] },
        { name: 'Archer Pull-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'], details: 'Advanced unilateral.' },
        { name: 'Typewriter Pull-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'], details: 'Advanced.' },
        { name: 'Lat Pulldown', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['machines', 'cable'] },
        { name: 'Wide Grip Lat Pulldown', type: 'compound', muscles: ['Lats'], equipment: ['machines', 'cable'] },
        { name: 'Single Arm Lat Pulldown', type: 'compound', muscles: ['Lats'], equipment: ['cable', 'machines'] },
        { name: 'Close Grip Lat Pulldown', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['machines', 'cable'] },
        { name: 'Straight Arm Pulldown', type: 'isolation', muscles: ['Lats'], equipment: ['cable', 'bands'] },
        // Other Rows & Machines
        { name: 'Seated Cable Row', type: 'compound', muscles: ['Lats', 'Rhomboids', 'Biceps'], equipment: ['machines', 'cable'] },
        { name: 'Machine Row', type: 'compound', muscles: ['Mid-Back', 'Lats'], equipment: ['machines'] },
        { name: 'Machine Pullover', type: 'isolation', muscles: ['Lats'], equipment: ['machines'] },
        { name: 'Inverted Row (Bodyweight Row)', type: 'compound', muscles: ['Upper Back', 'Biceps'], equipment: ['bodyweight', 'barbell'] },
        // Rear Delts & Lower Back
        { name: 'Face Pulls', type: 'isolation', muscles: ['Rear Delts', 'Rhomboids'], equipment: ['cable', 'bands'] },
        { name: 'Back Extension (Hyperextension)', type: 'isolation', muscles: ['Lower Back', 'Glutes'], equipment: ['bodyweight', 'machines'] },
        { name: 'Good Mornings', type: 'compound', muscles: ['Hamstrings', 'Glutes', 'Lower Back'], equipment: ['barbell'] },
        { name: 'Superman Holds', type: 'isolation', muscles: ['Lower Back'], equipment: ['bodyweight'] },
    ],
    'Legs': [
        // Squats
        { name: 'Barbell Back Squat', type: 'compound', muscles: ['Quads', 'Glutes', 'Hamstrings'], equipment: ['barbell'] },
        { name: 'Front Squat', type: 'compound', muscles: ['Quads', 'Core', 'Glutes'], equipment: ['barbell'] },
        { name: 'Box Squat', type: 'compound', muscles: ['Quads', 'Glutes', 'Hamstrings'], equipment: ['barbell'] },
        { name: 'Smith Machine Squat', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['machines'] },
        { name: 'Goblet Squat', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['dumbbells', 'kettlebell'] },
        { name: 'Bulgarian Split Squats', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['dumbbells', 'bodyweight'] },
        { name: 'Bodyweight Squat', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['bodyweight'] },
        { name: 'Pistol Squat (or progressions)', type: 'compound', muscles: ['Quads', 'Glutes', 'Balance'], equipment: ['bodyweight'], details: 'Advanced unilateral.' },
        { name: 'Sissy Squat', type: 'isolation', muscles: ['Quads'], equipment: ['bodyweight'] },
        { name: 'Shrimp Squat', type: 'compound', muscles: ['Quads', 'Glutes', 'Balance'], equipment: ['bodyweight'], details: 'Advanced unilateral.' },
        { name: 'Jump Squats', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['bodyweight'], details: 'Plyometric.' },
        { name: 'Hack Squat', type: 'compound', muscles: ['Quads'], equipment: ['machines'] },
        // Hip Hinges
        { name: 'Romanian Deadlifts (RDL)', type: 'compound', muscles: ['Hamstrings', 'Glutes'], equipment: ['barbell', 'dumbbells'] },
        { name: 'Single Leg RDL', type: 'compound', muscles: ['Hamstrings', 'Glutes', 'Balance'], equipment: ['dumbbells', 'kettlebell'] },
        // Lunges
        { name: 'Walking Lunges', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['dumbbells', 'bodyweight'] },
        { name: 'Reverse Lunges', type: 'compound', muscles: ['Glutes', 'Quads'], equipment: ['dumbbells', 'bodyweight'] },
        { name: 'Lateral Lunges', type: 'compound', muscles: ['Adductors', 'Glutes', 'Quads'], equipment: ['dumbbells', 'bodyweight'] },
        { name: 'Jumping Lunges', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['bodyweight'], details: 'Plyometric.' },
        // Machines
        { name: 'Leg Press', type: 'compound', muscles: ['Quads', 'Glutes', 'Hamstrings'], equipment: ['machines'] },
        { name: 'Leg Extensions', type: 'isolation', muscles: ['Quads'], equipment: ['machines'] },
        { name: 'Seated Hamstring Curl', type: 'isolation', muscles: ['Hamstrings'], equipment: ['machines'] },
        { name: 'Lying Hamstring Curl', type: 'isolation', muscles: ['Hamstrings'], equipment: ['machines'] },
        { name: 'Nordic Hamstring Curl', type: 'isolation', muscles: ['Hamstrings'], equipment: ['bodyweight'] },
        { name: 'Hip Abduction Machine', type: 'isolation', muscles: ['Glute Medius'], equipment: ['machines'] },
        { name: 'Hip Adduction Machine', type: 'isolation', muscles: ['Adductors'], equipment: ['machines'] },
        // Glutes & Calves
        { name: 'Hip Thrusts', type: 'compound', muscles: ['Glutes', 'Hamstrings'], equipment: ['barbell', 'dumbbells', 'bands'] },
        { name: 'Glute Bridge', type: 'compound', muscles: ['Glutes'], equipment: ['bodyweight', 'barbell'] },
        { name: 'Single Leg Glute Bridge', type: 'compound', muscles: ['Glutes'], equipment: ['bodyweight'] },
        { name: 'Standing Calf Raises', type: 'isolation', muscles: ['Calves'], equipment: ['dumbbells', 'machines', 'bodyweight'] },
        { name: 'Seated Calf Raises', type: 'isolation', muscles: ['Soleus'], equipment: ['machines'] },
        { name: 'Calf Press on Leg Press', type: 'isolation', muscles: ['Calves'], equipment: ['machines'] },
        // Other
        { name: 'Kettlebell Swings', type: 'compound', muscles: ['Glutes', 'Hamstrings', 'Core'], equipment: ['kettlebell'] },
        { name: 'Step Ups', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['dumbbells', 'bodyweight'] },
    ],
    'Shoulders': [
        // Presses
        { name: 'Barbell Overhead Press (OHP)', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['barbell'] },
        { name: 'Seated Barbell Overhead Press', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['barbell'] },
        { name: 'Seated Dumbbell Press', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['dumbbells'] },
        { name: 'Smith Machine Overhead Press', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['machines'] },
        { name: 'Arnold Press', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['dumbbells'] },
        { name: 'Shoulder Press Machine', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['machines'] },
        { name: 'Landmine Press', type: 'compound', muscles: ['Anterior Delts', 'Pecs'], equipment: ['barbell'] },
        // Calisthenics Presses
        { name: 'Handstand Push-ups (or progressions)', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['bodyweight'], details: 'Wall-assisted or freestanding.' },
        { name: 'Pike Push-ups', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['bodyweight'] },
        // Lateral Raises
        { name: 'Dumbbell Lateral Raises', type: 'isolation', muscles: ['Lateral Delts'], equipment: ['dumbbells'] },
        { name: 'Cable Lateral Raise', type: 'isolation', muscles: ['Lateral Delts'], equipment: ['cable'] },
        { name: 'Leaning Lateral Raise', type: 'isolation', muscles: ['Lateral Delts'], equipment: ['dumbbells'] },
        { name: 'Machine Lateral Raise', type: 'isolation', muscles: ['Lateral Delts'], equipment: ['machines'] },
        // Front Raises
        { name: 'Dumbbell Front Raises', type: 'isolation', muscles: ['Anterior Delts'], equipment: ['dumbbells'] },
        { name: 'Cable Front Raise', type: 'isolation', muscles: ['Anterior Delts'], equipment: ['cable'] },
        { name: 'Plate Front Raise', type: 'isolation', muscles: ['Anterior Delts'], equipment: ['barbell'] }, // using a weight plate
        // Rear Delts
        { name: 'Bent-Over Dumbbell Raise', type: 'isolation', muscles: ['Rear Delts'], equipment: ['dumbbells'] },
        { name: 'Reverse Pec Deck', type: 'isolation', muscles: ['Rear Delts'], equipment: ['machines'] },
        { name: 'Face Pulls', type: 'isolation', muscles: ['Rear Delts', 'Rhomboids'], equipment: ['cable', 'bands'] },
        { name: 'Band Pull Apart', type: 'isolation', muscles: ['Rear Delts', 'Rhomboids'], equipment: ['bands'] },
        // Other
        { name: 'Barbell Shrugs', type: 'isolation', muscles: ['Traps'], equipment: ['barbell'] },
        { name: 'Dumbbell Shrugs', type: 'isolation', muscles: ['Traps'], equipment: ['dumbbells'] },
        { name: 'Upright Row', type: 'compound', muscles: ['Delts', 'Traps'], equipment: ['barbell', 'dumbbells', 'cable'] },
    ],
    'Arms': [
        // Biceps
        { name: 'Barbell Bicep Curl', type: 'isolation', muscles: ['Biceps'], equipment: ['barbell'] },
        { name: 'EZ Bar Curl', type: 'isolation', muscles: ['Biceps'], equipment: ['barbell'] },
        { name: 'Dumbbell Bicep Curl', type: 'isolation', muscles: ['Biceps'], equipment: ['dumbbells'] },
        { name: 'Hammer Curls', type: 'isolation', muscles: ['Biceps', 'Brachialis'], equipment: ['dumbbells', 'cable'] },
        { name: 'Incline Dumbbell Curl', type: 'isolation', muscles: ['Biceps'], equipment: ['dumbbells'] },
        { name: 'Concentration Curl', type: 'isolation', muscles: ['Biceps'], equipment: ['dumbbells'] },
        { name: 'Zottman Curl', type: 'isolation', muscles: ['Biceps', 'Forearms'], equipment: ['dumbbells'] },
        { name: 'Preacher Curls', type: 'isolation', muscles: ['Biceps'], equipment: ['machines', 'barbell', 'dumbbells'] },
        { name: 'Cable Bicep Curl', type: 'isolation', muscles: ['Biceps'], equipment: ['cable', 'bands'] },
        { name: 'Reverse Grip Curl', type: 'isolation', muscles: ['Brachialis', 'Forearms'], equipment: ['barbell'] },
        { name: 'Spider Curls', type: 'isolation', muscles: ['Biceps'], equipment: ['dumbbells', 'barbell'] },
        { name: 'Bodyweight Bicep Curls', type: 'isolation', muscles: ['Biceps'], equipment: ['bodyweight'], details: 'Use a bar or rings.' },
        // Triceps
        { name: 'Tricep Pushdowns (Rope)', type: 'isolation', muscles: ['Triceps'], equipment: ['cable', 'bands'] },
        { name: 'Tricep Pushdowns (Bar)', type: 'isolation', muscles: ['Triceps'], equipment: ['cable', 'bands'] },
        { name: 'Reverse Grip Tricep Pushdown', type: 'isolation', muscles: ['Triceps'], equipment: ['cable'] },
        { name: 'Skull Crushers', type: 'isolation', muscles: ['Triceps'], equipment: ['barbell', 'dumbbells'] },
        { name: 'Overhead Tricep Extension', type: 'isolation', muscles: ['Triceps'], equipment: ['dumbbells', 'cable'] },
        { name: 'JM Press', type: 'compound', muscles: ['Triceps'], equipment: ['barbell'] },
        { name: 'Dips (Tricep Focused)', type: 'compound', muscles: ['Triceps', 'Pecs', 'Delts'], equipment: ['bodyweight'] },
        { name: 'Bench Dips', type: 'compound', muscles: ['Triceps'], equipment: ['bodyweight'] },
        { name: 'Close Grip Bench Press', type: 'compound', muscles: ['Triceps', 'Chest'], equipment: ['barbell'] }, // Also in chest
        { name: 'Diamond Push-ups', type: 'compound', muscles: ['Triceps', 'Pecs'], equipment: ['bodyweight'] }, // Also in chest
        { name: 'Tricep Kickbacks', type: 'isolation', muscles: ['Triceps'], equipment: ['dumbbells', 'cable'] },
    ],
    'Forearms': [ // New Category
        { name: 'Barbell Wrist Curl', type: 'isolation', muscles: ['Forearms'], equipment: ['barbell'] },
        { name: 'Dumbbell Wrist Curl', type: 'isolation', muscles: ['Forearms'], equipment: ['dumbbells'] },
        { name: 'Barbell Reverse Wrist Curl', type: 'isolation', muscles: ['Forearms'], equipment: ['barbell'] },
        { name: 'Dumbbell Reverse Wrist Curl', type: 'isolation', muscles: ['Forearms'], equipment: ['dumbbells'] },
        { name: 'Farmer\'s Walk', type: 'compound', muscles: ['Forearms', 'Grip', 'Traps'], equipment: ['dumbbells', 'kettlebell'] },
        { name: 'Plate Pinch', type: 'isolation', muscles: ['Forearms', 'Grip'], equipment: ['barbell'] }, // using plates
    ],
    'Abs': [
        { name: 'Crunches', type: 'isolation', muscles: ['Upper Abs'], equipment: ['bodyweight'], details: 'Aim for 15-20 reps.' },
        { name: 'Decline Crunch', type: 'isolation', muscles: ['Upper Abs'], equipment: ['bodyweight'] },
        { name: 'Ab Crunch Machine', type: 'isolation', muscles: ['Abs'], equipment: ['machines'] },
        { name: 'Sit-Up', type: 'compound', muscles: ['Abs', 'Hip Flexors'], equipment: ['bodyweight'] },
        { name: 'Leg Raises', type: 'isolation', muscles: ['Lower Abs'], equipment: ['bodyweight'], details: 'Aim for 15-20 reps.' },
        { name: 'Hanging Leg Raises', type: 'isolation', muscles: ['Lower Abs', 'Core'], equipment: ['bodyweight'], details: 'AMRAP.' },
        { name: 'Hanging Knee Raises', type: 'isolation', muscles: ['Lower Abs'], equipment: ['bodyweight'] },
        { name: 'Toes to Bar', type: 'compound', muscles: ['Lower Abs', 'Core'], equipment: ['bodyweight'] },
        { name: 'Dragon Flag (or progressions)', type: 'compound', muscles: ['Core', 'Abs'], equipment: ['bodyweight'], details: 'Advanced.' },
        { name: 'Ab Rollout', type: 'compound', muscles: ['Core', 'Abs'], equipment: ['bodyweight'], details: 'Use ab wheel/barbell. 8-12 reps.' },
        { name: 'Plank', type: 'isolation', muscles: ['Core'], equipment: ['bodyweight'], details: 'Hold for 30-90 seconds.' },
        { name: 'Side Plank', type: 'isolation', muscles: ['Obliques'], equipment: ['bodyweight'], details: 'Hold for 30-60s per side.' },
        { name: 'Bicycle Crunches', type: 'isolation', muscles: ['Abs', 'Obliques'], equipment: ['bodyweight'], details: 'Aim for 20-40 total reps.' },
        { name: 'Russian Twists', type: 'isolation', muscles: ['Obliques'], equipment: ['bodyweight', 'dumbbells', 'kettlebell'] },
        { name: 'Side Bends', type: 'isolation', muscles: ['Obliques'], equipment: ['dumbbells', 'kettlebell'] },
        { name: 'Cable Crunches', type: 'isolation', muscles: ['Abs'], equipment: ['cable'] },
        { name: 'Cable Wood Chops', type: 'compound', muscles: ['Obliques', 'Core'], equipment: ['cable', 'bands'] },
        { name: 'Torso Rotation Machine', type: 'isolation', muscles: ['Obliques'], equipment: ['machines'] },
        { name: 'Pallof Press', type: 'isolation', muscles: ['Core', 'Obliques'], equipment: ['cable', 'bands'], details: 'Anti-rotation.' },
        { name: 'Heel Taps', type: 'isolation', muscles: ['Obliques'], equipment: ['bodyweight'] },
        { name: 'V-Ups', type: 'compound', muscles: ['Abs', 'Core'], equipment: ['bodyweight'] },
        { name: 'Seated Jackknife', type: 'compound', muscles: ['Abs', 'Core'], equipment: ['bodyweight'] },
        { name: 'Reverse Crunches', type: 'isolation', muscles: ['Lower Abs'], equipment: ['bodyweight'] },
        { name: 'Dead Bug', type: 'isolation', muscles: ['Core', 'Abs'], equipment: ['bodyweight'], details: 'Slow and controlled.' },
        { name: 'Hollow Body Hold', type: 'isolation', muscles: ['Core', 'Abs'], equipment: ['bodyweight'] },
        { name: 'Mountain Climbers', type: 'compound', muscles: ['Core', 'Cardio'], equipment: ['bodyweight'] },
        { name: 'Flutter Kicks', type: 'isolation', muscles: ['Lower Abs'], equipment: ['bodyweight'] },
    ],
    'Statics & Skills': [ // Calisthenics Category
        { name: 'Handstand Hold', type: 'skill', muscles: ['Shoulders', 'Core'], equipment: ['bodyweight'], details: 'Wall-assisted or freestanding.' },
        { name: 'L-Sit Hold', type: 'skill', muscles: ['Core', 'Triceps', 'Hips'], equipment: ['bodyweight'], details: 'On floor or parallettes.' },
        { name: 'Front Lever (or progressions)', type: 'skill', muscles: ['Back', 'Core', 'Biceps'], equipment: ['bodyweight'] },
        { name: 'Planche (or progressions)', type: 'skill', muscles: ['Shoulders', 'Chest', 'Core'], equipment: ['bodyweight'] },
        { name: 'Frog Stand', type: 'skill', muscles: ['Shoulders', 'Core', 'Balance'], equipment: ['bodyweight'] },
        { name: 'Back Lever (or progressions)', type: 'skill', muscles: ['Back', 'Biceps', 'Core'], equipment: ['bodyweight'] },
        { name: 'Muscle-up (or progressions)', type: 'skill', muscles: ['Back', 'Chest', 'Arms'], equipment: ['bodyweight'] },
    ],
    'Flexibility': [
        // Upper Body
        { name: 'Doorway Chest Stretch', type: 'stretch', muscles: ['Pecs', 'Shoulders'], equipment: ['bodyweight'], details: 'Hold for 30 seconds.' },
        { name: 'Triceps Stretch', type: 'stretch', muscles: ['Triceps', 'Shoulders'], equipment: ['bodyweight'], details: 'Hold for 30s each arm.' },
        { name: 'Cross Body Shoulder Stretch', type: 'stretch', muscles: ['Shoulders'], equipment: ['bodyweight'], details: 'Hold for 30s each arm.' },
        { name: 'Upper Back Stretch', type: 'stretch', muscles: ['Upper Back'], equipment: ['bodyweight'], details: 'Clasp hands and round your back.' },
        { name: 'Wrist Stretches', type: 'stretch', muscles: ['Forearms'], equipment: ['bodyweight'], details: 'Essential for calisthenics.' },
        // Lower Body
        { name: 'Standing Hamstring Stretch', type: 'stretch', muscles: ['Hamstrings'], equipment: ['bodyweight'], details: 'Hold for 30s each side.' },
        { name: 'Seated Forward Bend', type: 'stretch', muscles: ['Hamstrings', 'Back'], equipment: ['bodyweight'], details: 'Hold for 30-60 seconds.' },
        { name: 'Lying Quad Stretch', type: 'stretch', muscles: ['Quads'], equipment: ['bodyweight'], details: 'Hold for 30s each side.' },
        { name: 'Couch Stretch', type: 'stretch', muscles: ['Quads', 'Hip Flexors'], equipment: ['bodyweight'], details: 'Hold for 30-60s each side.' },
        { name: 'Butterfly Stretch', type: 'stretch', muscles: ['Inner Thighs'], equipment: ['bodyweight'], details: 'Sit tall and hold for 30-60 seconds.' },
        { name: 'Pigeon Pose', type: 'stretch', muscles: ['Hips', 'Glutes'], equipment: ['bodyweight'], details: 'Hold for 30-60s on each side.' },
        { name: 'Figure Four Stretch', type: 'stretch', muscles: ['Glutes', 'Hips'], equipment: ['bodyweight'] },
        { name: 'Calf Stretch', type: 'stretch', muscles: ['Calves'], equipment: ['bodyweight'], details: 'Lean against a wall.' },
        { name: 'Pancake Stretch', type: 'stretch', muscles: ['Hamstrings', 'Inner Thighs'], equipment: ['bodyweight'], details: 'Advanced.' },
        // Full Body & Spine
        { name: 'Downward Dog', type: 'stretch', muscles: ['Full Body'], equipment: ['bodyweight'], details: 'Hold for 30-60 seconds.' },
        { name: 'Cat-Cow Stretch', type: 'stretch', muscles: ['Spine'], equipment: ['bodyweight'], details: 'Flow for 60 seconds.' },
        { name: 'Cobra Pose', type: 'stretch', muscles: ['Abs', 'Spine'], equipment: ['bodyweight'], details: 'Hold for 20-30 seconds.' },
        { name: 'Child\'s Pose', type: 'stretch', muscles: ['Back', 'Hips'], equipment: ['bodyweight'], details: 'Rest and hold for 60 seconds.' },
        { name: 'World\'s Greatest Stretch', type: 'stretch', muscles: ['Full Body', 'Hips'], equipment: ['bodyweight'], details: '5-8 reps per side.' },
        { name: 'Spinal Twist', type: 'stretch', muscles: ['Spine', 'Glutes'], equipment: ['bodyweight'] },
        { name: 'Bridge', type: 'stretch', muscles: ['Spine', 'Hips', 'Pecs'], equipment: ['bodyweight'], details: 'Advanced.' },
    ],
    'Cardio': [
        { name: 'Treadmill Running', type: 'cardio', muscles: ['Full Body'], equipment: ['cardio'] },
        { name: 'Treadmill Walking', type: 'cardio', muscles: ['Full Body'], equipment: ['cardio'] },
        { name: 'Elliptical Trainer', type: 'cardio', muscles: ['Full Body'], equipment: ['cardio'] },
        { name: 'Stationary Bike', type: 'cardio', muscles: ['Legs'], equipment: ['cardio'] },
        { name: 'Rowing Machine', type: 'cardio', muscles: ['Full Body'], equipment: ['cardio'] },
        { name: 'Stair Climber', type: 'cardio', muscles: ['Legs', 'Glutes'], equipment: ['cardio'] },
        { name: 'Jumping Jacks', type: 'cardio', muscles: ['Full Body'], equipment: ['bodyweight'] },
        { name: 'Burpees', type: 'cardio', muscles: ['Full Body'], equipment: ['bodyweight'] },
        { name: 'High Knees', type: 'cardio', muscles: ['Full Body'], equipment: ['bodyweight'] },
        { name: 'Jump Rope', type: 'cardio', muscles: ['Full Body'], equipment: ['bodyweight'] },
    ]
};

const cardioRoutines = {
    treadmill: "5 mins: Brisk walk (warmup). 5-10 mins: Jog. Optional: 2-3 rounds of (1 min sprint, 2 mins walk). 5 mins: Cool-down walk.",
    elliptical: "5 mins: Easy pace, low resistance (warmup). Increase resistance every 2 mins for 10 mins. Keep a steady, challenging pace. 5 mins: Cool-down with low resistance.",
    bike: "5 mins: Easy pedaling (warmup). 5-10 mins: Increase resistance. Optional: Tabata (20s sprint, 10s rest for 4 mins). 5 mins: Cool-down.",
    rower: "5 mins: Slow, controlled rows (warmup). 5-10 mins: Row for distance (e.g., 2000m) at a strong, steady pace. 5 mins: Cool-down."
};