// --- DATABASE ---
const exerciseDB = {
    'Chest': [
        { name: 'Push-ups', type: 'compound', muscles: ['Pecs', 'Triceps', 'Core'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Incline Push-ups', type: 'compound', muscles: ['Pecs', 'Triceps', 'Core'], equipment: ['bodyweight'], difficulty: 'beginner', details: 'Easier variation of standard push-ups.' },
        { name: 'Dumbbell Bench Press', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['dumbbells'], difficulty: 'beginner' },
        { name: 'Machine Chest Press', type: 'compound', muscles: ['Pecs', 'Triceps'], equipment: ['machines'], difficulty: 'beginner' },
        { name: 'Dumbbell Flyes', type: 'isolation', muscles: ['Pecs'], equipment: ['dumbbells'], difficulty: 'beginner' },
        { name: 'Bench Press', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['barbell'], difficulty: 'intermediate' },
        { name: 'Incline Dumbbell Press', type: 'compound', muscles: ['Upper Pecs', 'Delts'], equipment: ['dumbbells'], difficulty: 'intermediate' },
        { name: 'Dips', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Cable Crossover', type: 'isolation', muscles: ['Pecs'], equipment: ['cable'], difficulty: 'intermediate' },
        { name: 'Decline Bench Press', type: 'compound', muscles: ['Lower Pecs', 'Triceps'], equipment: ['barbell', 'dumbbells'], difficulty: 'advanced' },
        { name: 'Weighted Dips', type: 'compound', muscles: ['Pecs', 'Triceps', 'Delts'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'One-Arm Push-up', type: 'compound', muscles: ['Pecs', 'Triceps', 'Core'], equipment: ['bodyweight'], difficulty: 'advanced' },
    ],
    'Back': [
        { name: 'Bodyweight Row', type: 'compound', muscles: ['Back', 'Biceps'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Dumbbell Row', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['dumbbells'], difficulty: 'beginner' },
        { name: 'Lat Pulldown', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['machines', 'cable'], difficulty: 'beginner' },
        { name: 'Seated Cable Row', type: 'compound', muscles: ['Lats', 'Rhomboids', 'Biceps'], equipment: ['machines', 'cable'], difficulty: 'beginner' },
        { name: 'Back Extension', type: 'isolation', muscles: ['Lower Back'], equipment: ['bodyweight', 'machines'], difficulty: 'beginner' },
        { name: 'Pull-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Barbell Bent Over Row', type: 'compound', muscles: ['Lats', 'Rhomboids', 'Biceps'], equipment: ['barbell'], difficulty: 'intermediate' },
        { name: 'T-Bar Row', type: 'compound', muscles: ['Lats', 'Mid-Back'], equipment: ['barbell', 'machines'], difficulty: 'intermediate' },
        { name: 'Face Pulls', type: 'isolation', muscles: ['Rear Delts', 'Rhomboids'], equipment: ['cable', 'bands'], difficulty: 'intermediate' },
        { name: 'Weighted Pull-ups', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'Muscle-up', type: 'compound', muscles: ['Lats', 'Biceps', 'Triceps', 'Chest'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'One-Arm Dumbbell Row', type: 'compound', muscles: ['Lats', 'Biceps'], equipment: ['dumbbells'], difficulty: 'advanced' },
    ],
    'Legs': [
        { name: 'Bodyweight Squats', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Lunges', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['bodyweight', 'dumbbells'], difficulty: 'beginner' },
        { name: 'Goblet Squat', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['dumbbells', 'kettlebell'], difficulty: 'beginner' },
        { name: 'Leg Press', type: 'compound', muscles: ['Quads', 'Glutes', 'Hamstrings'], equipment: ['machines'], difficulty: 'beginner' },
        { name: 'Leg Extensions', type: 'isolation', muscles: ['Quads'], equipment: ['machines'], difficulty: 'beginner' },
        { name: 'Hamstring Curls', type: 'isolation', muscles: ['Hamstrings'], equipment: ['machines'], difficulty: 'beginner' },
        { name: 'Calf Raises', type: 'isolation', muscles: ['Calves'], equipment: ['bodyweight', 'dumbbells'], difficulty: 'beginner' },
        { name: 'Squats', type: 'compound', muscles: ['Quads', 'Glutes', 'Hamstrings'], equipment: ['barbell'], difficulty: 'intermediate' },
        { name: 'Romanian Deadlifts (RDL)', type: 'compound', muscles: ['Hamstrings', 'Glutes'], equipment: ['barbell', 'dumbbells'], difficulty: 'intermediate' },
        { name: 'Bulgarian Split Squats', type: 'compound', muscles: ['Quads', 'Glutes'], equipment: ['dumbbells'], difficulty: 'intermediate' },
        { name: 'Hip Thrusts', type: 'compound', muscles: ['Glutes', 'Hamstrings'], equipment: ['barbell', 'dumbbells'], difficulty: 'intermediate' },
        { name: 'Deadlifts', type: 'compound', muscles: ['Glutes', 'Hamstrings', 'Lower Back'], equipment: ['barbell'], difficulty: 'advanced' },
        { name: 'Pistol Squat', type: 'compound', muscles: ['Quads', 'Glutes', 'Core'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'Overhead Squat', type: 'compound', muscles: ['Quads', 'Glutes', 'Shoulders', 'Core'], equipment: ['barbell'], difficulty: 'advanced' },
    ],
    'Glutes': [ // Added for more specific targeting
        { name: 'Glute Bridge', type: 'isolation', muscles: ['Glutes'], equipment: ['bodyweight', 'dumbbells'], difficulty: 'beginner' },
        { name: 'Fire Hydrants', type: 'isolation', muscles: ['Glutes'], equipment: ['bodyweight', 'bands'], difficulty: 'beginner' },
        { name: 'Cable Pull Through', type: 'compound', muscles: ['Glutes', 'Hamstrings'], equipment: ['cable'], difficulty: 'intermediate' },
        { name: 'Single-Leg Hip Thrust', type: 'compound', muscles: ['Glutes', 'Hamstrings'], equipment: ['bodyweight', 'dumbbells'], difficulty: 'advanced' },
    ],
    'Shoulders': [
        { name: 'Pike Push-ups', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Dumbbell Lateral Raises', type: 'isolation', muscles: ['Lateral Delts'], equipment: ['dumbbells'], difficulty: 'beginner' },
        { name: 'Front Raises', type: 'isolation', muscles: ['Anterior Delts'], equipment: ['dumbbells'], difficulty: 'beginner' },
        { name: 'Overhead Press (OHP)', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['barbell', 'dumbbells'], difficulty: 'intermediate' },
        { name: 'Arnold Press', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['dumbbells'], difficulty: 'intermediate' },
        { name: 'Upright Row', type: 'compound', muscles: ['Delts', 'Traps'], equipment: ['barbell', 'dumbbells'], difficulty: 'intermediate' },
        { name: 'Handstand Push-ups', type: 'compound', muscles: ['Delts', 'Triceps'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'Z Press', type: 'compound', muscles: ['Delts', 'Triceps', 'Core'], equipment: ['barbell', 'dumbbells'], difficulty: 'advanced' },
    ],
    'Arms': [
        { name: 'Bicep Curls', type: 'isolation', muscles: ['Biceps'], equipment: ['dumbbells', 'bands'], difficulty: 'beginner' },
        { name: 'Tricep Dips (on bench)', type: 'isolation', muscles: ['Triceps'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Hammer Curls', type: 'isolation', muscles: ['Biceps', 'Brachialis'], equipment: ['dumbbells'], difficulty: 'beginner' },
        { name: 'Tricep Pushdowns', type: 'isolation', muscles: ['Triceps'], equipment: ['cable', 'bands'], difficulty: 'intermediate' },
        { name: 'Close Grip Bench Press', type: 'compound', muscles: ['Triceps', 'Chest'], equipment: ['barbell'], difficulty: 'intermediate' },
        { name: 'Skull Crushers', type: 'isolation', muscles: ['Triceps'], equipment: ['barbell', 'dumbbells'], difficulty: 'intermediate' },
        { name: 'Dragon Flag', type: 'compound', muscles: ['Biceps', 'Core'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'One-Arm Chin-up', type: 'compound', muscles: ['Biceps', 'Lats'], equipment: ['bodyweight'], difficulty: 'advanced' },
    ],
    'Abs': [
        { name: 'Crunches', type: 'isolation', muscles: ['Upper Abs'], equipment: ['bodyweight'], difficulty: 'beginner', details: 'Aim for 15-20 reps.' },
        { name: 'Leg Raises', type: 'isolation', muscles: ['Lower Abs'], equipment: ['bodyweight'], difficulty: 'beginner', details: 'Aim for 15-20 reps.' },
        { name: 'Plank', type: 'isolation', muscles: ['Core'], equipment: ['bodyweight'], difficulty: 'beginner', details: 'Hold for 30-60 seconds.' },
        { name: 'Hanging Knee Raises', type: 'isolation', muscles: ['Lower Abs', 'Core'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Ab Rollout', type: 'compound', muscles: ['Core', 'Abs'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Russian Twists', type: 'isolation', muscles: ['Obliques'], equipment: ['bodyweight', 'dumbbells'], difficulty: 'intermediate' },
        { name: 'L-Sit', type: 'compound', muscles: ['Core', 'Abs', 'Triceps'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'Toes to Bar', type: 'compound', muscles: ['Abs', 'Core', 'Lats'], equipment: ['bodyweight'], difficulty: 'advanced' },
    ],
    'Core': [ // Added for more specific targeting
        { name: 'Bird Dog', type: 'isolation', muscles: ['Core', 'Glutes'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Dead Bug', type: 'isolation', muscles: ['Core', 'Abs'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Pallof Press', type: 'isolation', muscles: ['Core', 'Obliques'], equipment: ['cable', 'bands'], difficulty: 'intermediate' },
        { name: 'Human Flag', type: 'compound', muscles: ['Core', 'Obliques', 'Lats'], equipment: ['bodyweight'], difficulty: 'advanced' },
    ],
    'Calisthenics': [ // New Category for skill-based movements
        { name: 'Scapular Pull-ups', type: 'isolation', muscles: ['Back'], equipment: ['bodyweight'], difficulty: 'beginner', details: 'Foundation for pull-ups.' },
        { name: 'Hollow Body Hold', type: 'isolation', muscles: ['Core'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Frog Stand', type: 'compound', muscles: ['Shoulders', 'Core'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Front Lever Tuck', type: 'compound', muscles: ['Back', 'Core'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Back Lever Tuck', type: 'compound', muscles: ['Chest', 'Core', 'Biceps'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Front Lever', type: 'compound', muscles: ['Back', 'Core'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'Back Lever', type: 'compound', muscles: ['Chest', 'Core', 'Biceps'], equipment: ['bodyweight'], difficulty: 'advanced' },
        { name: 'Planche Lean', type: 'compound', muscles: ['Shoulders', 'Core'], equipment: ['bodyweight'], difficulty: 'advanced' },
    ],
    'Flexibility': [
        { name: 'Downward Dog', type: 'stretch', muscles: ['Full Body'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Pigeon Pose', type: 'stretch', muscles: ['Hips', 'Glutes'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Cat-Cow Stretch', type: 'stretch', muscles: ['Spine'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Seated Forward Bend', type: 'stretch', muscles: ['Hamstrings', 'Back'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Lying Quad Stretch', type: 'stretch', muscles: ['Quads'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Doorway Chest Stretch', type: 'stretch', muscles: ['Pecs', 'Shoulders'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Butterfly Stretch', type: 'stretch', muscles: ['Inner Thighs'], equipment: ['bodyweight'], difficulty: 'beginner' },
        { name: 'Couch Stretch', type: 'stretch', muscles: ['Quads', 'Hip Flexors'], equipment: ['bodyweight'], difficulty: 'intermediate' },
        { name: 'Pancake Stretch', type: 'stretch', muscles: ['Hamstrings', 'Adductors'], equipment: ['bodyweight'], difficulty: 'advanced' },
    ],
};

const cardioRoutines = {
    treadmill: "5 mins: Brisk walk (warmup). 5-10 mins: Jog. Optional: 2-3 rounds of (1 min sprint, 2 mins walk). 5 mins: Cool-down walk.",
    elliptical: "5 mins: Easy pace, low resistance (warmup). Increase resistance every 2 mins for 10 mins. Keep a steady, challenging pace. 5 mins: Cool-down with low resistance.",
    bike: "5 mins: Easy pedaling (warmup). 5-10 mins: Increase resistance. Optional: Tabata (20s sprint, 10s rest for 4 mins). 5 mins: Cool-down.",
    rower: "5 mins: Slow, controlled rows (warmup). 5-10 mins: Row for distance (e.g., 2000m) at a strong, steady pace. 5 mins: Cool-down rows."
};